module1-task3
htmlacademy-nodejs/592167-typoteka-3 pull request #3
Opened 2020-01-29 09:45 UTC by Agafon87

2020-01-29 16:19 UTC, mairovichaa requested changes

2020-01-29 16:19 UTC, Flerki commented on .gitignore
> +mocks.json
в задании `mock.json`

2020-01-29 16:19 UTC, Flerki commented on src/constants.js
> +  success: 0,
Объявляй, пожалуйста, константы заглавными буквами

2020-01-29 16:19 UTC, Flerki commented on src/service/cli/generate.js
> +const FILE_NAME = `mocks.json`;
Замени на `mock.json`, пожалуйста

2020-01-29 16:19 UTC, Flerki commented on src/service/cli/help.js
> +    server <command>
Добавь, пожалуйста, корректное описание того, как запускать

2020-01-31 12:19 UTC, Flerki commented on src/service/cli/help.js
> +  console.log(`Программа запускает http-сервер и формирует файл с данными для API.
Программа не запускает http-сервер

2020-02-05 09:11 UTC, Agafon87 commented on src/service/cli/help.js
> +  console.log(`Программа запускает http-сервер и формирует файл с данными для API.
Убрал фразу о запуске http-сервера

2020-02-09 10:35 UTC, merged